// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoc/numerical.proto

package go_micro_srv_numerical

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Array struct {
	Ints                 []int32  `protobuf:"varint,1,rep,packed,name=ints" json:"ints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Array) Reset()         { *m = Array{} }
func (m *Array) String() string { return proto.CompactTextString(m) }
func (*Array) ProtoMessage()    {}
func (*Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_numerical_9bcfc3d28318127c, []int{0}
}
func (m *Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Array.Unmarshal(m, b)
}
func (m *Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Array.Marshal(b, m, deterministic)
}
func (dst *Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Array.Merge(dst, src)
}
func (m *Array) XXX_Size() int {
	return xxx_messageInfo_Array.Size(m)
}
func (m *Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Array.DiscardUnknown(m)
}

var xxx_messageInfo_Array proto.InternalMessageInfo

func (m *Array) GetInts() []int32 {
	if m != nil {
		return m.Ints
	}
	return nil
}

type StringArray struct {
	S                    []string `protobuf:"bytes,1,rep,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_numerical_9bcfc3d28318127c, []int{1}
}
func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (dst *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(dst, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetS() []string {
	if m != nil {
		return m.S
	}
	return nil
}

type Integer struct {
	Int                  int32    `protobuf:"varint,1,opt,name=int" json:"int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integer) Reset()         { *m = Integer{} }
func (m *Integer) String() string { return proto.CompactTextString(m) }
func (*Integer) ProtoMessage()    {}
func (*Integer) Descriptor() ([]byte, []int) {
	return fileDescriptor_numerical_9bcfc3d28318127c, []int{2}
}
func (m *Integer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integer.Unmarshal(m, b)
}
func (m *Integer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integer.Marshal(b, m, deterministic)
}
func (dst *Integer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integer.Merge(dst, src)
}
func (m *Integer) XXX_Size() int {
	return xxx_messageInfo_Integer.Size(m)
}
func (m *Integer) XXX_DiscardUnknown() {
	xxx_messageInfo_Integer.DiscardUnknown(m)
}

var xxx_messageInfo_Integer proto.InternalMessageInfo

func (m *Integer) GetInt() int32 {
	if m != nil {
		return m.Int
	}
	return 0
}

type String struct {
	S                    string   `protobuf:"bytes,1,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_numerical_9bcfc3d28318127c, []int{3}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (dst *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(dst, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type Response struct {
	Result               int32    `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_numerical_9bcfc3d28318127c, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Array)(nil), "go.micro.srv.numerical.Array")
	proto.RegisterType((*StringArray)(nil), "go.micro.srv.numerical.StringArray")
	proto.RegisterType((*Integer)(nil), "go.micro.srv.numerical.Integer")
	proto.RegisterType((*String)(nil), "go.micro.srv.numerical.String")
	proto.RegisterType((*Response)(nil), "go.micro.srv.numerical.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NumericalService service

type NumericalServiceClient interface {
	SumArray(ctx context.Context, in *Array, opts ...grpc.CallOption) (*Response, error)
	SumWords(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*String, error)
}

type numericalServiceClient struct {
	cc *grpc.ClientConn
}

func NewNumericalServiceClient(cc *grpc.ClientConn) NumericalServiceClient {
	return &numericalServiceClient{cc}
}

func (c *numericalServiceClient) SumArray(ctx context.Context, in *Array, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.numerical.NumericalService/SumArray", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numericalServiceClient) SumWords(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/go.micro.srv.numerical.NumericalService/SumWords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NumericalService service

type NumericalServiceServer interface {
	SumArray(context.Context, *Array) (*Response, error)
	SumWords(context.Context, *StringArray) (*String, error)
}

func RegisterNumericalServiceServer(s *grpc.Server, srv NumericalServiceServer) {
	s.RegisterService(&_NumericalService_serviceDesc, srv)
}

func _NumericalService_SumArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Array)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumericalServiceServer).SumArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.numerical.NumericalService/SumArray",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumericalServiceServer).SumArray(ctx, req.(*Array))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumericalService_SumWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumericalServiceServer).SumWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.numerical.NumericalService/SumWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumericalServiceServer).SumWords(ctx, req.(*StringArray))
	}
	return interceptor(ctx, in, info, handler)
}

var _NumericalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.numerical.NumericalService",
	HandlerType: (*NumericalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SumArray",
			Handler:    _NumericalService_SumArray_Handler,
		},
		{
			MethodName: "SumWords",
			Handler:    _NumericalService_SumWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/numerical.proto",
}

func init() { proto.RegisterFile("protoc/numerical.proto", fileDescriptor_numerical_9bcfc3d28318127c) }

var fileDescriptor_numerical_9bcfc3d28318127c = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x1b, 0xea, 0xae, 0x75, 0xf4, 0x50, 0xe6, 0xb0, 0x94, 0x16, 0x65, 0x89, 0x97, 0x9e,
	0x22, 0xe8, 0x13, 0x78, 0xf4, 0xa0, 0x60, 0xf6, 0xe0, 0xb9, 0xc6, 0x61, 0x09, 0x74, 0x93, 0x32,
	0xc9, 0x16, 0x7c, 0x2f, 0x1f, 0x50, 0x9a, 0x18, 0xf1, 0x60, 0x7b, 0x9b, 0xe4, 0xfb, 0xbf, 0x64,
	0x66, 0xa0, 0xd9, 0xb1, 0x8f, 0xde, 0xdc, 0xb9, 0x71, 0x20, 0xb6, 0x66, 0xb3, 0x55, 0xe9, 0x02,
	0x9b, 0xde, 0xab, 0xc1, 0x1a, 0xf6, 0x2a, 0xf0, 0x5e, 0xfd, 0x52, 0xb9, 0x82, 0xea, 0x91, 0x79,
	0xf3, 0x89, 0x08, 0x67, 0xd6, 0xc5, 0xb0, 0x10, 0xed, 0x74, 0x5d, 0xe9, 0x54, 0xcb, 0x15, 0x5c,
	0x76, 0x91, 0xad, 0xeb, 0x73, 0xe4, 0x0a, 0x44, 0xe6, 0x17, 0x5a, 0x1c, 0xe0, 0xf9, 0x93, 0x8b,
	0xd4, 0x13, 0xe3, 0x1c, 0xa6, 0xd6, 0xc5, 0x85, 0x68, 0xc5, 0xba, 0xd2, 0x87, 0x52, 0x36, 0x50,
	0x67, 0xb3, 0x48, 0x22, 0x4b, 0x12, 0x66, 0x9a, 0xc2, 0xce, 0xbb, 0x40, 0xd8, 0x40, 0xcd, 0x14,
	0xc6, 0x6d, 0x11, 0x7f, 0x4e, 0xf7, 0x5f, 0x02, 0xe6, 0x2f, 0xa5, 0xc1, 0x8e, 0x78, 0x6f, 0x0d,
	0xe1, 0x33, 0xcc, 0xba, 0x71, 0xc8, 0x7d, 0x5c, 0xab, 0xff, 0x87, 0x51, 0x09, 0x2f, 0xdb, 0x63,
	0xb8, 0xfc, 0x2c, 0x27, 0xf8, 0x9a, 0x9e, 0x7b, 0xf3, 0xfc, 0x11, 0xf0, 0xf6, 0x58, 0xfe, 0xcf,
	0xec, 0xcb, 0x9b, 0xd3, 0x21, 0x39, 0x79, 0xaf, 0xd3, 0xa2, 0x1f, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0x29, 0xdc, 0x72, 0x82, 0x01, 0x00, 0x00,
}
